import * as path from 'path';
import { Configuration } from 'webpack';
import { ConsoleRemotePlugin } from '@openshift-console/dynamic-plugin-sdk-webpack';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const config: Configuration = {
  mode: 'production',
  entry: {}, // Entry is auto-generated by ConsoleRemotePlugin
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name]-bundle.js',
    chunkFilename: '[name]-chunk.js',
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.jsx'],
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
      },
    ],
  },
  plugins: [
    new ConsoleRemotePlugin({
      pluginMetadata: {
        name: 'placement-discovery-plugin',
        version: '0.3.0',
        displayName: 'Placement Topology',
        description: 'Visualize pod and VM placement across cluster nodes',
        exposedModules: {
          PodTab: './src/components/PlacementTopology/PodTab',
          DeploymentTab: './src/components/PlacementTopology/DeploymentTab',
          VMTab: './src/components/PlacementTopology/VMTab',
        },
        dependencies: {
          '@console/pluginAPI': '*',
        },
      },
      extensions: [
        {
          type: 'console.tab/horizontalNav',
          properties: {
            page: {
              name: 'Placement',
              href: 'placement',
            },
            model: {
              group: 'core',
              version: 'v1',
              kind: 'Pod',
            },
            component: {
              $codeRef: 'PodTab',
            },
          },
        },
        {
          type: 'console.tab/horizontalNav',
          properties: {
            page: {
              name: 'Placement',
              href: 'placement',
            },
            model: {
              group: 'apps',
              version: 'v1',
              kind: 'Deployment',
            },
            component: {
              $codeRef: 'DeploymentTab',
            },
          },
        },
        {
          type: 'console.tab/horizontalNav',
          properties: {
            page: {
              name: 'Placement',
              href: 'placement',
            },
            model: {
              group: 'kubevirt.io',
              version: 'v1',
              kind: 'VirtualMachine',
            },
            component: {
              $codeRef: 'VMTab',
            },
          },
        },
      ],
    }),
  ],
  devtool: process.env.NODE_ENV === 'development' ? 'source-map' : false,
  performance: {
    hints: false,
  },
};

export default config;
